# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow2(object):
    def setupUi(self, mainWindow2):
        mainWindow2.setObjectName("mainWindow2")
        mainWindow2.setWindowModality(QtCore.Qt.NonModal)
        mainWindow2.resize(1213, 878)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        mainWindow2.setFont(font)
        mainWindow2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow2.setWindowIcon(icon)
        mainWindow2.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(mainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 351, 751))
        self.groupBox.setObjectName("groupBox")
        self.tblwHesap = QtWidgets.QTableWidget(self.groupBox)
        self.tblwHesap.setGeometry(QtCore.QRect(10, 90, 331, 571))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tblwHesap.setFont(font)
        self.tblwHesap.setRowCount(10)
        self.tblwHesap.setColumnCount(3)
        self.tblwHesap.setObjectName("tblwHesap")
        self.tblwHesap.horizontalHeader().setVisible(True)
        self.tblwHesap.horizontalHeader().setCascadingSectionResizes(False)
        self.tblwHesap.horizontalHeader().setDefaultSectionSize(100)
        self.tblwHesap.horizontalHeader().setHighlightSections(True)
        self.btnOde = QtWidgets.QPushButton(self.groupBox)
        self.btnOde.setGeometry(QtCore.QRect(10, 700, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOde.setFont(font)
        self.btnOde.setObjectName("btnOde")
        self.btnSil = QtWidgets.QPushButton(self.groupBox)
        self.btnSil.setGeometry(QtCore.QRect(120, 700, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.btnDusur = QtWidgets.QPushButton(self.groupBox)
        self.btnDusur.setGeometry(QtCore.QRect(240, 700, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDusur.setFont(font)
        self.btnDusur.setObjectName("btnDusur")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblToplamFiyat = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblToplamFiyat.setFont(font)
        self.lblToplamFiyat.setObjectName("lblToplamFiyat")
        self.horizontalLayout.addWidget(self.lblToplamFiyat)
        self.rdbtnNakit = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtnNakit.setGeometry(QtCore.QRect(10, 670, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdbtnNakit.setFont(font)
        self.rdbtnNakit.setObjectName("rdbtnNakit")
        self.rdbtnKart = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtnKart.setGeometry(QtCore.QRect(220, 670, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdbtnKart.setFont(font)
        self.rdbtnKart.setObjectName("rdbtnKart")
        self.btnAnaEkranaGeriDon = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnaEkranaGeriDon.setGeometry(QtCore.QRect(20, 780, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAnaEkranaGeriDon.setFont(font)
        self.btnAnaEkranaGeriDon.setObjectName("btnAnaEkranaGeriDon")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 20, 381, 751))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnSicakIcecek = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSicakIcecek.setGeometry(QtCore.QRect(10, 40, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSicakIcecek.setFont(font)
        self.btnSicakIcecek.setObjectName("btnSicakIcecek")
        self.btnSogukIcecek = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSogukIcecek.setGeometry(QtCore.QRect(200, 40, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSogukIcecek.setFont(font)
        self.btnSogukIcecek.setObjectName("btnSogukIcecek")
        self.btnEspresso = QtWidgets.QPushButton(self.groupBox_2)
        self.btnEspresso.setGeometry(QtCore.QRect(10, 140, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEspresso.setFont(font)
        self.btnEspresso.setObjectName("btnEspresso")
        self.btnDunya = QtWidgets.QPushButton(self.groupBox_2)
        self.btnDunya.setGeometry(QtCore.QRect(200, 140, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDunya.setFont(font)
        self.btnDunya.setObjectName("btnDunya")
        self.btnDondurmali = QtWidgets.QPushButton(self.groupBox_2)
        self.btnDondurmali.setGeometry(QtCore.QRect(200, 240, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDondurmali.setFont(font)
        self.btnDondurmali.setObjectName("btnDondurmali")
        self.btnSerinleten = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSerinleten.setGeometry(QtCore.QRect(10, 240, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSerinleten.setFont(font)
        self.btnSerinleten.setObjectName("btnSerinleten")
        self.btnTost = QtWidgets.QPushButton(self.groupBox_2)
        self.btnTost.setGeometry(QtCore.QRect(10, 540, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnTost.setFont(font)
        self.btnTost.setObjectName("btnTost")
        self.btnBaslangic = QtWidgets.QPushButton(self.groupBox_2)
        self.btnBaslangic.setGeometry(QtCore.QRect(10, 440, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBaslangic.setFont(font)
        self.btnBaslangic.setObjectName("btnBaslangic")
        self.btnSandvic = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSandvic.setGeometry(QtCore.QRect(200, 440, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSandvic.setFont(font)
        self.btnSandvic.setObjectName("btnSandvic")
        self.btnFrozen = QtWidgets.QPushButton(self.groupBox_2)
        self.btnFrozen.setGeometry(QtCore.QRect(10, 340, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnFrozen.setFont(font)
        self.btnFrozen.setObjectName("btnFrozen")
        self.btnYumurta = QtWidgets.QPushButton(self.groupBox_2)
        self.btnYumurta.setGeometry(QtCore.QRect(200, 540, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnYumurta.setFont(font)
        self.btnYumurta.setObjectName("btnYumurta")
        self.btnMilkshake = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMilkshake.setGeometry(QtCore.QRect(200, 340, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMilkshake.setFont(font)
        self.btnMilkshake.setObjectName("btnMilkshake")
        self.btnGozleme = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGozleme.setGeometry(QtCore.QRect(10, 640, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGozleme.setFont(font)
        self.btnGozleme.setObjectName("btnGozleme")
        self.btnKahvalti = QtWidgets.QPushButton(self.groupBox_2)
        self.btnKahvalti.setGeometry(QtCore.QRect(200, 640, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKahvalti.setFont(font)
        self.btnKahvalti.setObjectName("btnKahvalti")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(790, 20, 401, 751))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lstwUrunler = QtWidgets.QListWidget(self.groupBox_3)
        self.lstwUrunler.setGeometry(QtCore.QRect(20, 40, 361, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstwUrunler.setFont(font)
        self.lstwUrunler.setObjectName("lstwUrunler")
        item = QtWidgets.QListWidgetItem()
        self.lstwUrunler.addItem(item)
        self.btnIkiEkle = QtWidgets.QPushButton(self.groupBox_3)
        self.btnIkiEkle.setGeometry(QtCore.QRect(211, 430, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIkiEkle.setFont(font)
        self.btnIkiEkle.setObjectName("btnIkiEkle")
        self.btnEkle = QtWidgets.QPushButton(self.groupBox_3)
        self.btnEkle.setGeometry(QtCore.QRect(20, 430, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEkle.setFont(font)
        self.btnEkle.setObjectName("btnEkle")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 780, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblMasaNo = QtWidgets.QLabel(self.centralwidget)
        self.lblMasaNo.setGeometry(QtCore.QRect(520, 780, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblMasaNo.setFont(font)
        self.lblMasaNo.setObjectName("lblMasaNo")
        mainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 21))
        self.menubar.setObjectName("menubar")
        mainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow2)
        self.statusbar.setObjectName("statusbar")
        mainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow2)

    def retranslateUi(self, mainWindow2):
        _translate = QtCore.QCoreApplication.translate
        mainWindow2.setWindowTitle(_translate("mainWindow2", "Adisyon Programı"))
        self.groupBox.setTitle(_translate("mainWindow2", "Hesap"))
        self.btnOde.setText(_translate("mainWindow2", "ÖDE"))
        self.btnSil.setText(_translate("mainWindow2", "SİL"))
        self.btnDusur.setText(_translate("mainWindow2", "DÜŞÜR"))
        self.label.setText(_translate("mainWindow2", "Toplam :"))
        self.lblToplamFiyat.setText(_translate("mainWindow2", "x TL"))
        self.rdbtnNakit.setText(_translate("mainWindow2", "Nakit"))
        self.rdbtnKart.setText(_translate("mainWindow2", "Kart"))
        self.btnAnaEkranaGeriDon.setText(_translate("mainWindow2", "ANA EKRANA GERİ DÖN"))
        self.groupBox_2.setTitle(_translate("mainWindow2", "Ürün Çeşitleri"))
        self.btnSicakIcecek.setText(_translate("mainWindow2", "Sıcak İçecekler"))
        self.btnSogukIcecek.setText(_translate("mainWindow2", "Soğuk İçecekler"))
        self.btnEspresso.setText(_translate("mainWindow2", "Espresso Kahveler"))
        self.btnDunya.setText(_translate("mainWindow2", "Dünya Kahveleri"))
        self.btnDondurmali.setText(_translate("mainWindow2", "Kokteyler"))
        self.btnSerinleten.setText(_translate("mainWindow2", "Serinleten Kahveler"))
        self.btnTost.setText(_translate("mainWindow2", "Tostlar"))
        self.btnBaslangic.setText(_translate("mainWindow2", "Başlangıçlar"))
        self.btnSandvic.setText(_translate("mainWindow2", "Sandviçler"))
        self.btnFrozen.setText(_translate("mainWindow2", "Frozen"))
        self.btnYumurta.setText(_translate("mainWindow2", "Yumurtalar"))
        self.btnMilkshake.setText(_translate("mainWindow2", "Milkshake"))
        self.btnGozleme.setText(_translate("mainWindow2", "Gözlemeler"))
        self.btnKahvalti.setText(_translate("mainWindow2", "Kahvaltılar"))
        self.groupBox_3.setTitle(_translate("mainWindow2", "Ürünler"))
        __sortingEnabled = self.lstwUrunler.isSortingEnabled()
        self.lstwUrunler.setSortingEnabled(False)
        item = self.lstwUrunler.item(0)
        item.setText(_translate("mainWindow2", "deneme"))
        self.lstwUrunler.setSortingEnabled(__sortingEnabled)
        self.btnIkiEkle.setText(_translate("mainWindow2", "İKİ TANE EKLE"))
        self.btnEkle.setText(_translate("mainWindow2", "EKLE"))
        self.label_2.setText(_translate("mainWindow2", "Masa Numarası: "))
        self.lblMasaNo.setText(_translate("mainWindow2", "x"))

