# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masalarUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.resize(1210, 890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Çeşitli dosyalar/fotograf/634601_python_512x512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 1171, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btnMasa1 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa1.setGeometry(QtCore.QRect(10, 30, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa1.setFont(font)
        self.btnMasa1.setObjectName("btnMasa1")
        self.btnMasa2 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa2.setGeometry(QtCore.QRect(240, 30, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa2.setFont(font)
        self.btnMasa2.setObjectName("btnMasa2")
        self.btnMasa3 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa3.setGeometry(QtCore.QRect(470, 30, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa3.setFont(font)
        self.btnMasa3.setObjectName("btnMasa3")
        self.btnMasa4 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa4.setGeometry(QtCore.QRect(710, 30, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa4.setFont(font)
        self.btnMasa4.setObjectName("btnMasa4")
        self.btnMasa5 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa5.setGeometry(QtCore.QRect(940, 30, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa5.setFont(font)
        self.btnMasa5.setObjectName("btnMasa5")
        self.btnMasa10 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa10.setGeometry(QtCore.QRect(940, 150, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa10.setFont(font)
        self.btnMasa10.setObjectName("btnMasa10")
        self.btnMasa6 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa6.setGeometry(QtCore.QRect(10, 150, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa6.setFont(font)
        self.btnMasa6.setObjectName("btnMasa6")
        self.btnMasa7 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa7.setGeometry(QtCore.QRect(240, 150, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa7.setFont(font)
        self.btnMasa7.setObjectName("btnMasa7")
        self.btnMasa8 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa8.setGeometry(QtCore.QRect(470, 150, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa8.setFont(font)
        self.btnMasa8.setObjectName("btnMasa8")
        self.btnMasa9 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa9.setGeometry(QtCore.QRect(710, 150, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa9.setFont(font)
        self.btnMasa9.setObjectName("btnMasa9")
        self.btnMasa16 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa16.setGeometry(QtCore.QRect(10, 390, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa16.setFont(font)
        self.btnMasa16.setObjectName("btnMasa16")
        self.btnMasa19 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa19.setGeometry(QtCore.QRect(710, 390, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa19.setFont(font)
        self.btnMasa19.setObjectName("btnMasa19")
        self.btnMasa11 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa11.setGeometry(QtCore.QRect(10, 270, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa11.setFont(font)
        self.btnMasa11.setObjectName("btnMasa11")
        self.btnMasa12 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa12.setGeometry(QtCore.QRect(240, 270, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa12.setFont(font)
        self.btnMasa12.setObjectName("btnMasa12")
        self.btnMasa20 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa20.setGeometry(QtCore.QRect(940, 390, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa20.setFont(font)
        self.btnMasa20.setObjectName("btnMasa20")
        self.btnMasa15 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa15.setGeometry(QtCore.QRect(940, 270, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa15.setFont(font)
        self.btnMasa15.setObjectName("btnMasa15")
        self.btnMasa13 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa13.setGeometry(QtCore.QRect(470, 270, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa13.setFont(font)
        self.btnMasa13.setObjectName("btnMasa13")
        self.btnMasa14 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa14.setGeometry(QtCore.QRect(710, 270, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa14.setFont(font)
        self.btnMasa14.setObjectName("btnMasa14")
        self.btnMasa17 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa17.setGeometry(QtCore.QRect(240, 390, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa17.setFont(font)
        self.btnMasa17.setObjectName("btnMasa17")
        self.btnMasa18 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa18.setGeometry(QtCore.QRect(470, 390, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa18.setFont(font)
        self.btnMasa18.setObjectName("btnMasa18")
        self.btnMasa26 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa26.setGeometry(QtCore.QRect(10, 630, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa26.setFont(font)
        self.btnMasa26.setObjectName("btnMasa26")
        self.btnMasa27 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa27.setGeometry(QtCore.QRect(240, 630, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa27.setFont(font)
        self.btnMasa27.setObjectName("btnMasa27")
        self.btnMasa23 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa23.setGeometry(QtCore.QRect(470, 510, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa23.setFont(font)
        self.btnMasa23.setObjectName("btnMasa23")
        self.btnMasa25 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa25.setGeometry(QtCore.QRect(940, 510, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa25.setFont(font)
        self.btnMasa25.setObjectName("btnMasa25")
        self.btnMasa22 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa22.setGeometry(QtCore.QRect(240, 510, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa22.setFont(font)
        self.btnMasa22.setObjectName("btnMasa22")
        self.btnMasa29 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa29.setGeometry(QtCore.QRect(710, 630, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa29.setFont(font)
        self.btnMasa29.setObjectName("btnMasa29")
        self.btnMasa28 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa28.setGeometry(QtCore.QRect(470, 630, 231, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa28.setFont(font)
        self.btnMasa28.setObjectName("btnMasa28")
        self.btnMasa30 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa30.setGeometry(QtCore.QRect(940, 630, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa30.setFont(font)
        self.btnMasa30.setObjectName("btnMasa30")
        self.btnMasa24 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa24.setGeometry(QtCore.QRect(710, 510, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa24.setFont(font)
        self.btnMasa24.setObjectName("btnMasa24")
        self.btnMasa21 = QtWidgets.QPushButton(self.groupBox)
        self.btnMasa21.setGeometry(QtCore.QRect(10, 510, 220, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMasa21.setFont(font)
        self.btnMasa21.setObjectName("btnMasa21")
        self.btnGunuKapa = QtWidgets.QPushButton(self.centralwidget)
        self.btnGunuKapa.setGeometry(QtCore.QRect(960, 780, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGunuKapa.setFont(font)
        self.btnGunuKapa.setObjectName("btnGunuKapa")
        self.lblTarih = QtWidgets.QLabel(self.centralwidget)
        self.lblTarih.setGeometry(QtCore.QRect(30, 780, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lblTarih.setFont(font)
        self.lblTarih.setObjectName("lblTarih")
        self.lblKasaGorevlisi = QtWidgets.QLabel(self.centralwidget)
        self.lblKasaGorevlisi.setGeometry(QtCore.QRect(190, 780, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lblKasaGorevlisi.setFont(font)
        self.lblKasaGorevlisi.setObjectName("lblKasaGorevlisi")
        MainWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1210, 21))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        self.menu_leti_im = QtWidgets.QMenu(self.menuYard_m)
        self.menu_leti_im.setObjectName("menu_leti_im")
        MainWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow1)
        self.statusbar.setObjectName("statusbar")
        MainWindow1.setStatusBar(self.statusbar)
        self.actionCihan_ayindi_hotmail_com = QtWidgets.QAction(MainWindow1)
        self.actionCihan_ayindi_hotmail_com.setObjectName("actionCihan_ayindi_hotmail_com")
        self.menu_leti_im.addAction(self.actionCihan_ayindi_hotmail_com)
        self.menuYard_m.addAction(self.menu_leti_im.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "Masalar"))
        self.groupBox.setTitle(_translate("MainWindow1", "Masalar"))
        self.btnMasa1.setText(_translate("MainWindow1", "MASA 1"))
        self.btnMasa2.setText(_translate("MainWindow1", "MASA 2"))
        self.btnMasa3.setText(_translate("MainWindow1", "MASA 3"))
        self.btnMasa4.setText(_translate("MainWindow1", "MASA 4"))
        self.btnMasa5.setText(_translate("MainWindow1", "MASA 5"))
        self.btnMasa10.setText(_translate("MainWindow1", "MASA 10"))
        self.btnMasa6.setText(_translate("MainWindow1", "MASA 6"))
        self.btnMasa7.setText(_translate("MainWindow1", "MASA 7"))
        self.btnMasa8.setText(_translate("MainWindow1", "MASA 8"))
        self.btnMasa9.setText(_translate("MainWindow1", "MASA 9"))
        self.btnMasa16.setText(_translate("MainWindow1", "MASA 16"))
        self.btnMasa19.setText(_translate("MainWindow1", "MASA 19"))
        self.btnMasa11.setText(_translate("MainWindow1", "MASA 11"))
        self.btnMasa12.setText(_translate("MainWindow1", "MASA 12"))
        self.btnMasa20.setText(_translate("MainWindow1", "MASA 20"))
        self.btnMasa15.setText(_translate("MainWindow1", "MASA 15"))
        self.btnMasa13.setText(_translate("MainWindow1", "MASA 13"))
        self.btnMasa14.setText(_translate("MainWindow1", "MASA 14"))
        self.btnMasa17.setText(_translate("MainWindow1", "MASA 17"))
        self.btnMasa18.setText(_translate("MainWindow1", "MASA 18"))
        self.btnMasa26.setText(_translate("MainWindow1", "MASA 26"))
        self.btnMasa27.setText(_translate("MainWindow1", "MASA 27"))
        self.btnMasa23.setText(_translate("MainWindow1", "MASA 23"))
        self.btnMasa25.setText(_translate("MainWindow1", "MASA 25"))
        self.btnMasa22.setText(_translate("MainWindow1", "MASA 22"))
        self.btnMasa29.setText(_translate("MainWindow1", "MASA 29"))
        self.btnMasa28.setText(_translate("MainWindow1", "MASA 28"))
        self.btnMasa30.setText(_translate("MainWindow1", "MASA 30"))
        self.btnMasa24.setText(_translate("MainWindow1", "MASA 24"))
        self.btnMasa21.setText(_translate("MainWindow1", "MASA 21"))
        self.btnGunuKapa.setText(_translate("MainWindow1", "GÜNÜ KAPAT"))
        self.lblTarih.setText(_translate("MainWindow1", "10/12/2000"))
        self.lblKasaGorevlisi.setText(_translate("MainWindow1", "Kasa Görevlisi: x"))
        self.menuYard_m.setTitle(_translate("MainWindow1", "Yardım"))
        self.menu_leti_im.setTitle(_translate("MainWindow1", "İletişim"))
        self.actionCihan_ayindi_hotmail_com.setText(_translate("MainWindow1", "cihan_ayindi@hotmail.com"))

